services:
  spring:
    build:
      context: ..
      dockerfile: ctoip_docker/Dockerfile.spring
    image: ghcr.io/ctoip/ctoip-backend:${IMAGE_TAG:-latest}

  web:
    build:
      context: ..
      dockerfile: ctoip_docker/Dockerfile.web
    image: ghcr.io/ctoip/ctoip-frontend:${IMAGE_TAG:-latest}
