From nginx:1.22.1
MAINTAINER Aurora

ENV HTMLPATH /usr/share/nginx/html
ENV NGINXPATH /etc/nginx
ARG SERVERIP
ARG DISTFILE
ARG NGINXCONF

ADD ${DISTFILE} $HTMLPATH/dist/
ADD ${NGINXCONF} ${NGINXPATH}/

WORKDIR $HTMLPATH/dist

RUN tar -xzvf dist.tar.gz

WORKDIR $NGINXPATH
RUN mv nginx.conf tmpnginx.conf \
    && envsubst '${HTMLPATH},${SERVERIP}' < tmpnginx.conf > nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

