FROM node:16-bullseye AS builder

WORKDIR /workspace/ctoip_vue
COPY ctoip_vue/package*.json ./
RUN npm ci
COPY ctoip_vue/ ./
RUN npm run build

FROM nginx:1.27-alpine

COPY ctoip_docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /workspace/ctoip_vue/dist /usr/share/nginx/html/dist

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
